export const companyKeywords: {
  [key: string]: { jobTitle: string; defaultKeywords: string[] };
} = {
  altis: {
    jobTitle: "Senior Software Engineer",
    defaultKeywords: [
      "cloudcomputing",
      "fullstack",
      "leadership",
      "projectmanagement",
      "softwarearchitecture",
      "systemdesign",
      "javascript",
      "reactjs",
      "graphql",
      "datascience",
      "aws",
      "communication",
      "distributedsystems",
      "Networking",
    ],
  },
  dockermanager: {
    jobTitle: "Manager, Engineer",
    defaultKeywords: [
      "fullstack",
      "leadership",
      "projectmanagement",
      "communication",
      "softwarearchitecture",
      "systemdesign",
      "aws",
      "javascript",
      "react",
      "distributedsystems",
      "c++",
      "teaching",
    ],
  },
  dockerstaffse: {
    jobTitle: "Staff Software Engineer (Frontend Platform)",
    defaultKeywords: [
      "fullstack",
      "leadership",
      "projectmanagement",
      "testing",
      "communication",
      "softwarearchitecture",
      "systemdesign",
      "aws",
      "javascript",
      "react",
      "distributedsystems",
      "c++",
      "teaching",
    ],
  },
};
