export const companyKeywords: {
  [key: string]: { jobTitle: string; defaultKeywords: string[] };
} = {
  altis: {
    jobTitle: "Senior Software Engineer",
    defaultKeywords: [
      "cloudcomputing",
      "fullstack",
      "leadership",
      "projectmanagement",
      "softwarearchitecture",
      "systemdesign",
      "javascript",
      "reactjs",
      "graphql",
      "datascience",
      "aws",
      "communication",
      "distributedsystems",
      "Networking",
    ],
  },
  dockermanager: {
    jobTitle: "Manager, Engineer",
    defaultKeywords: [
      "fullstack",
      "leadership",
      "projectmanagement",
      "communication",
      "softwarearchitecture",
      "systemdesign",
      "aws",
      "javascript",
      "react",
      "distributedsystems",
      "c++",
      "teaching",
    ],
  },
  dockerstaffse: {
    jobTitle: "Staff Software Engineer (Frontend Platform)",
    defaultKeywords: [
      "fullstack",
      "leadership",
      "projectmanagement",
      "testing",
      "communication",
      "softwarearchitecture",
      "systemdesign",
      "aws",
      "javascript",
      "react",
      "distributedsystems",
      "c++",
      "teaching",
    ],
  },
  fieldeffect: {
    jobTitle: "Senior Software Developer",
    defaultKeywords: [
      "python",
      "database",
      "communication",
      "docker",
      "backend",
      "api",
      "systemdesign",
      "datascience",
      "networking",
      "distributedsystems",
      "networking",
      "testing",
      "leadership",
      "aws",
      "django",
      "fieldeffect",
      "networking",
      "cloud",
    ],
  },
  slackfrontend: {
    jobTitle: "Senior Software Engineer - Frontend",
    defaultKeywords: [
      "fullstack",
      "javascript",
      "websocket",
      "mobileapp",
      "communication",
    ],
  },
  slackbackend: {
    jobTitle: "Senior Software Engineer - Backend",
    defaultKeywords: [
      "systemdesign",
      "distributedsystems",
      "communication",
      "testing",
      "softwarearchitecture",
      "python",
      "research",
      "leadership",
      "backend",
      "networking",
      "api",
      "graphql",
      "projectmanagement",
      "cloudcomputing",
    ],
  },
};
